version: '3'

services:
  api-service:
    build: 
      context: .
      dockerfile: dockerfolder/dockerfile
    volumes:
      - ~/dockerfolder:/app
    ports:
      - 8080:8080
    restart: always
    network_mode: host
